import Head from 'next/head';
import NavBar from '../components/Navbar';
import Slider from '../components/slider';
import BestCategories from '../components/bestcategories';
import Topselling from '../components/topselling';
import Tshirt from '../components/thirt';
import JoinNewsLetter from '../components/joinnewsLetter';
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Slider />
      <BestCategories />
      <Topselling />
      <Tshirt />
      <JoinNewsLetter />
      <Footer />


    </div>
  )
}
